export default{
  category:[
    '热销榜',
    '天天特价',
    '汤圆',
    '巧克力',
    '优选水果',
    '卤味熟食',
    '牛奶面包',
    '饮料酒水',
    '休闲零食',
    '方便素食',
    '生活用品',
    '粮油调味',
    '冰激凌',
    '代购星巴克'
  ],
  hot:[{
    name:'爱鲜蜂·赣南脐橙',
    img:require('./images/home/mock/fruit/orange_jscheng.jpg'),
    recommend:true,
    standard:'80g/盒',
    unitPrice:15.00,
    originalPrice:30
  },{
    name:'爱鲜蜂·四川春见丑柑',
    img:require('./images/home/mock/fruit/orange_sichuan.jpg'),
    recommend:true,
    standard:'200g',
    unitPrice:10,
    originalPrice:30
  },{
    name:'爱鲜蜂·砂糖橘',
    img:require('./images/home/mock/fruit/orange_shatang.jpg'),
    recommend:true,
    standard:'10g/盒',
    unitPrice:23,
    originalPrice:30
  }]
}
