export default{
  category:[
    '热销榜',
    '天天特价',
    '汤圆',
    '巧克力',
    '优选水果',
    '卤味熟食',
    '牛奶面包',
    '饮料酒水',
    '休闲零食',
    '方便素食',
    '生活用品',
    '粮油调味',
    '冰激凌',
    '代购星巴克'
  ],
  hot:[{
    name:'爱鲜蜂·赣南脐橙',
    img:require('./images/home/mock/fruit/orange_jscheng.jpg'),
    recommend:true,
    standard:'80g/盒',
    unitPrice:15.00,
    originalPrice:30
  },{
    name:'爱鲜蜂·四川春见丑柑',
    img:require('./images/home/mock/fruit/orange_sichuan.jpg'),
    recommend:true,
    standard:'200g',
    unitPrice:10,
    originalPrice:30
  },{
    name:'爱鲜蜂·砂糖橘',
    img:require('./images/home/mock/fruit/orange_shatang.jpg'),
    recommend:true,
    standard:'10g/盒',
    unitPrice:23,
    originalPrice:30
  }],
  supermarket:{
    hot:[{
      name:'蜂觅·越南红心火龙果',
      img:require('./images/supermarket/hot/huolongguo.jpg'),
      standard:'350-450g/盒',
      unitPrice:35,
      originalPrice:50
    },{
      name:'爱鲜蜂·打火机',
      img:require('./images/supermarket/hot/dahuoji.jpg'),
      standard:'1个',
      unitPrice:2,
      originalPrice:0
    },{
      name:'3M9001V专业防护口罩',
      img:require('./images/supermarket/hot/kouzhao.jpg'),
      standard:'3个/袋',
      unitPrice:22.8,
      originalPrice:30
    },{
      name:'爱鲜蜂·砂糖橘',
      img:require('./images/supermarket/hot/shatangju.jpg'),
      standard:'480-550g/盒',
      unitPrice:2,
      originalPrice:0
    },{
      name:'爱鲜蜂·高原红富士',
      img:require('./images/supermarket/hot/apple.jpg'),
      standard:'380-420g 2粒/盒',
      unitPrice:17.6,
      originalPrice:28
    },{
      name:'飘香鸭锁骨(微辣)',
      img:require('./images/supermarket/hot/yabo.jpg'),
      standard:'220g',
      unitPrice:16,
      originalPrice:20
    },{
      name:'味全活性乳酸菌饮料原味',
      img:require('./images/supermarket/hot/weiquan.jpg'),
      standard:'435ml',
      unitPrice:6.9,
      originalPrice:0
    }]
  }
}
