export default {
  banner:[
    require('./images/home/banner1.jpeg'),
    require('./images/home/banner2.jpeg')
  ],
  quickEntry:[{
    name:'每日签到',
    imgSrc:require('./images/home/quickIcon1.png')
  },{
    name:'疯狂秒杀',
    imgSrc:require('./images/home/quickIcon2.png')
  },{
    name:'鲜货直供',
    imgSrc:require('./images/home/quickIcon3.png')
  },{
    name:'整箱购',
    imgSrc:require('./images/home/quickIcon4.png')
  }],
  specilSell:[
    require('./images/home/specilSellItem1.jpeg'),
    require('./images/home/specilSellItem2.jpeg'),
    require('./images/home/specilSellItem3.jpeg')
  ],
  themeSpline:require('./images/home/themeSpline.png'),
  hotTheme:require('./images/home/hotSell.jpeg'),
  everyDaySell:require('./images/home/everyDaySpecialSell.jpeg'),
  business:[{
    name:'牛奶面包',
    imgSrc:require('./images/home/milk.png')
  },{
    name:'饮料酒水',
    imgSrc:require('./images/home/drink.png')
  },{
    name:'优选水果',
    imgSrc:require('./images/home/fruit.png')
  },{
    name:'更多',
    imgSrc:require('./images/home/homeMore.png')
  }],
}
