export default {
  banner:[
    require('./images/home/banner1.jpeg'),
    require('./images/home/banner2.jpeg')
  ],
  quickEntry:[{
    name:'每日签到',
    imgSrc:require('./images/home/quickIcon1.png')
  },{
    name:'疯狂秒杀',
    imgSrc:require('./images/home/quickIcon2.png')
  },{
    name:'鲜货直供',
    imgSrc:require('./images/home/quickIcon3.png')
  },{
    name:'整箱购',
    imgSrc:require('./images/home/quickIcon4.png')
  }],
  specilSell:[
    require('./images/home/specilSellItem1.jpeg'),
    require('./images/home/specilSellItem2.jpeg'),
    require('./images/home/specilSellItem3.jpeg')
  ],
  themeSpline:require('./images/home/themeSpline.png'),
  hotTheme:require('./images/home/hotSell.jpeg'),
  everyDaySell:require('./images/home/everyDaySpecialSell.jpeg'),
  business:[{
    name:'牛奶面包',
    imgSrc:require('./images/home/milk.png')
  },{
    name:'饮料酒水',
    imgSrc:require('./images/home/drink.png')
  },{
    name:'优选水果',
    imgSrc:require('./images/home/fruit.png')
  },{
    name:'更多',
    imgSrc:require('./images/home/homeMore.png')
  }],
  hotSale:[
    require('./images/home/hotSale1.jpeg'),
    require('./images/home/hotSale2.jpeg'),
    require('./images/home/hotSale3.jpeg'),
    require('./images/home/hotSale4.png')
  ],
  categoryList:[
    {
      name:'优选水果',
      color:'yellow',
      headerStyle:{
        color:'#F38631',
      },
      bannerImg:require('./images/home/mock/fruit/banner.jpeg'),
      product:[{
        name:'爱鲜蜂·赣南脐橙',
        img:require('./images/home/mock/fruit/orange_jscheng.jpg'),
        recommend:true,
        standard:'80g/盒',
        unitPrice:15.00,
        originalPrice:30
      },{
        name:'爱鲜蜂·四川春见丑柑',
        img:require('./images/home/mock/fruit/orange_sichuan.jpg'),
        recommend:true,
        standard:'200g',
        unitPrice:10,
        originalPrice:30
      },{
        name:'爱鲜蜂·砂糖橘',
        img:require('./images/home/mock/fruit/orange_shatang.jpg'),
        recommend:true,
        standard:'10g/盒',
        unitPrice:23,
        originalPrice:30
      }]
    },{
        name:'牛奶面包',
        headerStyle:{
          color:'#20B1FA',
        },
        color:'yellow',
        bannerImg:require('./images/home/mock/milk/banner.jpeg'),
        product:[{
          name:'唯它香草味豆奶',
          img:require('./images/home/mock/milk/milk1.jpg'),
          recommend:true,
          standard:'250ml',
          unitPrice:6.00,
          originalPrice:30
        },{
          name:'哇哈哈AD钙奶',
          img:require('./images/home/mock/milk/wahaha.jpg'),
          recommend:true,
          standard:'150ml',
          unitPrice:8.00,
          originalPrice:30
        },{
          name:'养乐多五连装',
          img:require('./images/home/mock/milk/yangle.jpg'),
          recommend:true,
          standard:'100ml',
          unitPrice:7.5,
          originalPrice:30
        }]
    },
  ]
}
